version: "3.4"

networks:
  nst:

services:
  chat_server:
    container_name: chat_server
    image: node:latest
    working_dir: /app
    volumes:
    - ./:/app
    ports:
      - "31337:31337"
    networks:
      nst:
    command: "npm run prod"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:31337"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
